"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Nav } from "@/modules";
import { StateProvider } from "@/context/StateProvider";
import reducer from "@/context/reducer";
import { initialState } from "@/context/initialState";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <StateProvider reducer={reducer} initialState={initialState}>
            <Nav />
            <div className="p-4 pt-28">{children}</div>
          </StateProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
